# Generated by Django 4.2.1 on 2025-04-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_periodico_delete_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='logo',
            field=models.ImageField(max_length=200, upload_to='minerva/media/logos'),
        ),
    ]
