# Generated by Django 4.2.1 on 2025-04-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_periodico_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodico',
            name='logo',
            field=models.ImageField(blank=True, max_length=200, upload_to='logos'),
        ),
    ]
