# Generated by Django 4.2.1 on 2025-04-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_periodico_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre_rol',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('admin', 'admin'), ('prensa', 'prensa'), ('clasificacion', 'clasificacion'), ('redaccion', 'redaccion'), ('mapas', 'mapas'), ('estadistica', 'estadistica'), ('edicion', 'edicion'), ('publicacion', 'publicacion')], default='usuario', max_length=25),
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('periodico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.periodico')),
                ('responsableAcopio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'alta'), ('baja', 'baja'), ('modificacion', 'modificacion'), ('consulta', 'consulta'), ('lista', 'lista')], default='consulta', max_length=20)),
                ('entidad', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
