# Generated by Django 4.2.1 on 2025-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_nombre_rol_alter_profile_rol_link_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
