# Generated by Django 4.2.1 on 2025-04-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_actividad_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='responsableAcopio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
