# Generated by Django 4.2.1 on 2025-04-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_link_responsableacopio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
