# Generated by Django 4.2.1 on 2025-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('-', '-'), ('admin', 'admin'), ('prensa', 'prensa'), ('clasificacion', 'clasificacion'), ('redaccion', 'redaccion'), ('mapas', 'mapas'), ('estadistica', 'estadistica'), ('edicion', 'edicion'), ('publicacion', 'publicacion')], default='-', max_length=25),
        ),
    ]
